apiVersion: batch/v1
kind: CronJob
metadata:
  name: resume-generator-worker
  namespace: karyaquest-services
  labels:
    app.kubernetes.io/name: resume-generator-worker
spec:
  schedule: "*/5 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      labels:
        app.kubernetes.io/name: resume-generator-worker
    spec:
      backoffLimit: 0
      template:
        metadata:
          labels:
            app.kubernetes.io/name: resume-generator-worker
        spec:
          serviceAccountName: resume-generator-worker
          restartPolicy: Never
          containers:
            - name: resume-generator-worker
              image: karyaquest/resume-generator-worker:3200eb71063a
              imagePullPolicy: IfNotPresent
              env:
                - name: AGENT_API_URL
                  value: http://agent-api:8000
