apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: karyaquest-data
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: karyaquest
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/part-of: karyaquest
    spec:
      containers:
        - name: redis
          image: redis@sha256:02419de7eddf55aa5bcf49efb74e88fa8d931b4d77c07eff8a6b2144472b6952
          args:
            - redis-server
            - --appendonly
            - "no"
          ports:
            - name: redis
              containerPort: 6379
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 250m
              memory: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: karyaquest-data
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: karyaquest
spec:
  selector:
    app.kubernetes.io/name: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
