apiVersion: v1
kind: Secret
metadata:
    name: llm-gateway-openai
    namespace: karyaquest-services
type: Opaque
stringData:
    LLM_OPENAI_API_KEY: ENC[AES256_GCM,data:EmaWdipXzPnT411q/S2y4+IXh4NKf16P4PfvytegFCII7CWwu5KpeoRB6y7t9Hd4uXgvxkCMDQDi1N1+m3bpeEU171iV9h4M82Xo3NWxKOOkSzb7qIkYoR7bRBDIoo1GxSs+twAc3Otei4jRTzoT4An+O1KXRznQg9pwMuJoPvSSWTwBFiFZ+BB/7x0vGT9wAtr3EcXQQ+BXOSS/+m3ohI9eOWTe5jU=,iv:5ShHKg9jL2iKscwOIiBMT9SmuCvXwzsyg4GcWDvh4vA=,tag:SEIFz40EmKZKyGFrLZhq7w==,type:str]
sops:
    age:
        - recipient: age1tryrkl6twxk3wyszrhxf35cv5jt5xam05daff52t2sxaj6n56qnq2qyp2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSFNGL0o4bzBmaTRXZnBv
            VHBmUHdhKzh6bEJwM3pXSkVkRDBpL1hhNDM4CmRrWGlwRlhPd1FsT1Z1S1Y1Y0U0
            WFdqQmMxNFEzWnlxUFZZWnM5dkNaZXMKLS0tIG94TzNqMFl5NEdpZElZQnZZLzBQ
            RmpLSm9ZRW1IdE5aVWJjajNoVlhxa1EKTQXNbZs13pnIseSBjiyizHAFkDDmdSal
            RC6w8zCtxC5NfOSbCiRkZHokoe0fwpYG9Tc3EJKH08TVY1sMVq5YUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-15T22:39:54Z"
    mac: ENC[AES256_GCM,data:lg/18QT2xgGLlzpY70DfUEYoX8i735hnNES9hfUYXFjcXvqJFn6v7ctxkpLUJe9N0N2OJhl5hzATUcXDt3B+HeQ9lWo6fvst0rc7O1S9SVFemUJvNXR5TCQsxsUcZVn9A6279TvqMuRHBrIE+ls8VI1ExtkOyf5vlOOscpxJBxs=,iv:QIhkR1Jn/kv3kJfqPNM4gUdvA4dcnaow1NGZSMCO3aA=,tag:S7kL10hwPv7ygEItL8zkMw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
