apiVersion: v1
kind: Secret
metadata:
    name: llm-gateway-openai
    namespace: karyaquest-services
type: Opaque
stringData:
    LLM_OPENAI_API_KEY: ENC[AES256_GCM,data:EA0ULb/GdHlAMgM5eaX9WzPq1sQWUg1XXaxDnVg1SApQEFz5zL4G2hbzug/A+IXB7IOy55ATHsJ3hvU0S7uFVQLKNlSdBWfdLNNOxcfJjh8WoG6qyrbTdtDjSmOUOx7KqrOk0KaONNYM5lIBWm5Ay2hEmkWxpeh3YmnmoZ/RXdIAoJUddBEfobhyIRI40h1uZUcNC7kA49w3ti7E21Vr8yL3nGs=,iv:dJZOxeC+AtXIMO8fPYjBvf4My36VrrloooOnCpHPR68=,tag:gE/92XeFMXH0T4all7c4Og==,type:str]
sops:
    age:
        - recipient: age1tryrkl6twxk3wyszrhxf35cv5jt5xam05daff52t2sxaj6n56qnq2qyp2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaSFNGL0o4bzBmaTRXZnBv
            VHBmUHdhKzh6bEJwM3pXSkVkRDBpL1hhNDM4CmRrWGlwRlhPd1FsT1Z1S1Y1Y0U0
            WFdqQmMxNFEzWnlxUFZZWnM5dkNaZXMKLS0tIG94TzNqMFl5NEdpZElZQnZZLzBQ
            RmpLSm9ZRW1IdE5aVWJjajNoVlhxa1EKTQXNbZs13pnIseSBjiyizHAFkDDmdSal
            RC6w8zCtxC5NfOSbCiRkZHokoe0fwpYG9Tc3EJKH08TVY1sMVq5YUw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-24T03:56:26Z"
    mac: ENC[AES256_GCM,data:1eAgcguOYWmyPXu915FfpKBSaH9/b1FCw6Z0ldZ5wi6HFBSG2FgQB7rEOa/vTBCuMy94NE4ffJ4w7zcVOxqpswQL2fBpWDuP+KshC3q/quC1g/cqn/u+KY9IFQlm0WvaUYEzkysTds7JX9jscnujjbEHpFSuwBkH6OYpLFxuxl4=,iv:oQOn8ffaQVfwsEP9Aff19BcN6IzcQuFjCFtWW4zGsiw=,tag:IqhRXxxiW/S9dx/qdUOkYg==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
