apiVersion: v1
kind: Secret
metadata:
    name: minio-auth
    namespace: karyaquest-data
type: Opaque
stringData:
    MINIO_ROOT_USER: ENC[AES256_GCM,data:PQy8l/1hm6A+IQ==,iv:CyzveFKFoVr3X7GuYL1zHyu+Ux6+8A2I3uu9MG7pPkU=,tag:IrSjuQUl0UlA1tb9/y+wNA==,type:str]
    MINIO_ROOT_PASSWORD: ENC[AES256_GCM,data:KkN95aYUbnyhMXpgeuW7nx18RsRZ2/5WDIapXhyDScxO0T6S3mofvi7pMHo=,iv:atYrhYj24XSx9o/eoMFyVEQNvUxJFWjXWrc/Xer+DFA=,tag:wB3139LUmVhEgpz/RVOlYA==,type:str]
sops:
    age:
        - recipient: age1tryrkl6twxk3wyszrhxf35cv5jt5xam05daff52t2sxaj6n56qnq2qyp2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBscTkvVVZncC9XV09kaFNM
            M2phNHZEZXRhZUlxVmZYcXpaa3c1SXgrNHlNCjZhSU1mVWJaczBFMm5kam14Y3A3
            ZUM3aFl0ZGlNVmh5amhZeU1FN1RkZU0KLS0tIEl3anZVVGpjTWt0bGRZQkpzZGRG
            QzJuY0VpTW5nUGZoNUx6NElMMUoxWEEK0HZdXtExT/+cNNihPJpkkppKAI3ej7UP
            UC93xO08pH2QD4PFf4ADv+CSjPs9PvOe9DzCcNCnnikXy1oY6wi/ug==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-09T00:57:00Z"
    mac: ENC[AES256_GCM,data:6PSdRGQl3io7MWr1hKR9TWdwe4jCQRP4/rkQ0ScOXzkTH4UcDMczrT0wapzpuYhu0ZAQmKEOE5TRLpIlRyFLcW4+n3FZrNT1IC38Vu+iwrWy/x1ROwzAeQe48xY4fCU3G56G8/9py5rhXuovx+OxRnBmZiVFDCJ2zKIcZWcRS1o=,iv:TYFTLtzsP6CvMgc+KEwjZcu1YugmV0FrgliQfD4KLf4=,tag:0/7lXRgyuijA+Q3EYPAgmw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
