apiVersion: v1
data:
    POSTGRES_DB: ENC[AES256_GCM,data:0uC1irVSqhRjKUCgqGiIrw==,iv:pcS5p0LEPMNMxWbReXQd90qb1O6p0BGeF+Ufw+heRk4=,tag:J2D/yvPrxQjte7eqy8QGWw==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:4LwExEf8mSiQtJFZcJ4tRdeWb8eO/58iJoyyKBQusOyx6mcSYejl+DXmFR/URvN0Qjrj/oX4lWx1P0Mx,iv:6CGqY2siJr2NAL5oh1vgaB8Tze1MzKPM9eOhPNt/qUc=,tag:f0U7U+ThFfqq+Bd5vqnZ5w==,type:str]
    POSTGRES_USER: ENC[AES256_GCM,data:DEETgYzznwZVXiD+qRBIYQ==,iv:5RP6T+5rsrukb2AcjNGs7vvR13MnBzlBjl7nLs82LXA=,tag:jjF9H5sHBHZ1781exH5e1w==,type:str]
kind: Secret
metadata:
    name: postgres-auth
    namespace: karyaquest-data
type: Opaque
sops:
    age:
        - recipient: age1tryrkl6twxk3wyszrhxf35cv5jt5xam05daff52t2sxaj6n56qnq2qyp2p
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1K3p4WDVZQ1RZZkttUFV2
            dEFGcmhBQ0ZuQVh6S1ZPUWQ1K1B0c1IxRkhZCnp2djIrQlZPSE9iblpjQ3JpdFVl
            Sy9KUjFveXFMTVNOeHZSS05XbllLem8KLS0tIHlaN0djeDFER29HUlRyWHk0ZWov
            VHZnczJqeWsrUHNDcDhBVW1GSVBXRXMKp8ZJNpvu470TiIARWKShDHqF2WNgXTk1
            3dy9mhzVrCna20vWLc7pqKFFEWCU05FYG0xxTNxkrkay1MJqtEbbBA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-07-08T23:32:03Z"
    mac: ENC[AES256_GCM,data:tvNuEFXOmKvuuhoTJlI13zRQBJbQTmGdU1yKa5EvKVtyHnHuAu381qL5bkysAn63zZdRzPABMMYcWTw09NWVu7JzoVQhqUWdxVXciwCFR/MaVm0Qs38ivuo34zwAhQtvbg4Dew4upeHMquYfOTJeMEVOtDMeqAp67YmKPY44SrU=,iv:OlONOk19rI8LqgWdeGgrek2T92f9AQ1epIq6diJ9n3I=,tag:xX9zhZxNpP9e6241J/Rb2w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.12.1
