apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - postgres-migrate-001-initial-schema.yaml
  - postgres-migrate-002-profiles-resumes.yaml
  - postgres-migrate-003-resume-generation-approvals.yaml

configMapGenerator:
  - name: postgres-migrations
    files:
      - migrations/001_initial_schema.sql
      - migrations/002_profiles_resumes.sql
      - migrations/003_resume_generation_approvals.sql

generatorOptions:
  disableNameSuffixHash: true
