apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - postgres.yaml
  - postgres-migrate-001-initial-schema.yaml

configMapGenerator:
  - name: postgres-migrations
    files:
      - migrations/001_initial_schema.sql

generatorOptions:
  disableNameSuffixHash: true
