apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karyaquest-data
  namespace: argocd
spec:
  project: default
  source:
    repoURL: git@github.com:rajshkr71/karyaquest.git
    targetRevision: main
    path: deploy/overlays/local/data
  destination:
    server: https://kubernetes.default.svc
    namespace: karyaquest-data
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
